---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  strategy:  
    type: Recreate 
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      hostNetwork: true
      serviceAccountName: kubedoom
      containers:
      - name: kubedoom
        image: storaxdev/kubedoom:0.5.0
        ports:
        - containerPort: 5900 
          protocol: TCP


